services:
  postgres:
    image: postgres:latest
    container_name: rideshare_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d database"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis/redis-stack:latest
    container_name: rideshare_redis
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
  rabbitmq:
    image: rabbitmq:latest
    container_name: rideshare_rabbitmq
    environment:
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_USER: user
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
  server:
    build:
      context: ./core
      dockerfile: Dockerfile.local
    image: rideshare-core:latest
    container_name: rideshare_core
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/database
      DATASOURCE_USERNAME: user
      DATASOURCE_PASSWORD: password

      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: password

      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: unless-stopped
