services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
  redis:
    image: "redis/redis-stack:latest"
    container_name: redis_container
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
